name: Docker Backend Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Backend
      run: docker build backend --tag ebapp:$(date +%s)
